# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    weather_api_key: 04f3ecaa61866ac151eee1a4af5b22c1

services:
    app.weather:
        class: AppBundle\Weather\Weather
        arguments:
            - '@csa_guzzle.client.weather'
            - '@jms_serializer'
            - %weather_api_key%