# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    serializer_listener.article:
      class: AppBundle\Serializer\Listener\ArticleListener
      tags:
        - { name: jms_serializer.event_subcriber }