# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        provider.github_user:
            id: github_user_provider    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: github_authenticator
            provider: provider.github_user
        main:
            anonymous: ~